implement test example in ci

diff --git a/.github/workflows/partial-tests.yml b/.github/workflows/partial-tests.yml
--- a/.github/workflows/partial-tests.yml
+++ b/.github/workflows/partial-tests.yml
@@ -26,3 +26,23 @@ jobs:
 
       - name: Test
         run: go test ./... -race
+
+      - name: Test 'cli' example
+        run: |
+          go run main.go new --test hello
+          go run ./gen/main.go hello
+
+          # Run the command and store the output in a variable
+          output=$(gen run ./gen/main.go hello)
+
+          # Define the expected output
+          expected_output="Hello, your favorite colors are red, green"
+
+          # Compare the actual output with the expected output
+          if [ "$output" = "$expected_output" ]; then
+              echo "Test passed: Output matches the expected string."
+              exit 0
+          else
+              echo "Test failed: Output does not match the expected string."
+              exit 1
+          fi
